### PR TITLE
add conversion from SageMath

### PR DESCRIPTION
**Pull request by videlec**
Add a `sage_conversion.py` file in pyeantic to perform conversion from Sage `NumberField` to pyeantic.

### CODE REVIEW

**Comment by videlec** [comment]
@saraedum are you ok with having some doctests? I think that a minimum is useful for end users.

**Comment by saraedum** [comment]
Absolutely, there should be doctests. We should also run them on CI. SageMath is packaged on conda-forge so that's no problem but cppyy isn't yet…
Should I add more tests?

**Comment by videlec** [comment]
I created `doc.py` to run the doctests (and hence should be tested on CI). Tell me if you prefer another workflow.

**Comment by saraedum** [comment]
I tried to clean things up a bit. However, I get (and already got before my changes):
```
___________________________ test_construct_no_parent ___________________________

    def test_construct_no_parent():
>       assert eantic.renf_elem(1) == 1

renf_elem.py:50: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (1,)

    def py_make_renf_elem_class(*args):
        if len(args) == 1:
>           return eantic.renf_elem_class(args[0])
E           TypeError: Template method resolution failed. Full details:
E             none of the 11 overloaded methods succeeded. Full details:
E             renf_elem_class::renf_elem_class(eantic::renf_elem_class&&) =>
E               TypeError: could not convert argument 1
E             renf_elem_class::renf_elem_class(const eantic::renf_elem_class&) =>
E               TypeError: could not convert argument 1
E             renf_elem_class::renf_elem_class() =>
E               TypeError: takes at most 0 arguments (1 given)
E             renf_elem_class::renf_elem_class(const __gmp_expr<__mpz_struct[1],__mpz_struct[1]>&) =>
E               TypeError: could not convert argument 1
E             renf_elem_class::renf_elem_class(const __gmp_expr<__mpq_struct[1],__mpq_struct[1]>&) =>
E               TypeError: could not convert argument 1
E             renf_elem_class::renf_elem_class(fmpq[1]) =>
E               TypeError: could not convert argument 1
E             renf_elem_class::renf_elem_class(shared_ptr<const eantic::renf_class> k) =>
E               TypeError: could not convert argument 1
E             renf_elem_class::renf_elem_class(shared_ptr<const eantic::renf_class> k, const __gmp_expr<__mpz_struct[1],__mpz_struct[1]>&) =>
E               TypeError: takes at least 2 arguments (1 given)
E             renf_elem_class::renf_elem_class(shared_ptr<const eantic::renf_class> k, const __gmp_expr<__mpq_struct[1],__mpq_struct[1]>&) =>
E               TypeError: takes at least 2 arguments (1 given)
E             renf_elem_class::renf_elem_class(shared_ptr<const eantic::renf_class> k, fmpq[1]) =>
E               TypeError: takes at least 2 arguments (1 given)
E             renf_elem_class::renf_elem_class(shared_ptr<const eantic::renf_class> k, const string&) =>
E               TypeError: takes at least 2 arguments (1 given)
E             Failed to instantiate "renf_elem_class(int)"

../../src/pyeantic/pyeantic/cppyy_eantic.py:132: TypeError
====================== 1 failed, 4 passed in 0.79 seconds ======================
FAIL renf_elem.py (exit status: 1)
```

**Comment by saraedum** [comment]
@videlec: Are you not seeing that error? (Should I fix it?)

**Comment by videlec** [comment]
I do see the error. Not sure what happend.

**Comment by videlec** [comment]
Note that the template
```
    template <typename Integer, typename std::enable_if_t<std::is_integral_v<Integer>, int> = 0>
    renf_elem_class(Integer) noexcept;
```
is simply ignored.

**Comment by saraedum** [comment]
Yes, that's a known problem (to me.) Has this ever worked? Then it would be a regression in cppyy. Anyway, let me create an upstream issue and work around locally.

**Comment by saraedum** [comment]
I filed https://bitbucket.org/wlav/cppyy/issues/119/templatized-constructor-is-ignored upstream.

**Comment by saraedum** [comment]
So I guess this did not work earlier since there's https://github.com/flatsurf/pyeantic/issues/10.

**Pull request merged**
